batch_size: 32
block_num: 3
conf_hash: 82aef5a115
data_root: dataset
data_split:
- 864
- 288
- 288
dataset_name: AstramBengaluru
devices: 0,
dm: dm_multivariate
dow_emb_dim: 32
doy2embedding_path: AstramBengaluru/event_embeddings.pickle
eod_emb_dim: 32
eod_size: 3
es_patience: 5
exp_dir: save\STIDEF_AstramBengaluru\82aef5a115\seed_0
freq: 10
gradient_clip_val: 5
hist_len: 12
lr: 0.01
lr_scheduler: ReduceLROnPlateau
lrs_factor: 0.5
lrs_patience: 3
max_epochs: 5
max_event_per_day: 3
model_name: STIDEF
node_emb_dim: 32
null_value: 0.0
num_workers: 0
optimizer: Adam
optimizer_weight_decay: 1.0e-05
pred_len: 12
runner: traffic_forecasting_runner
save_root: save
seed: 0
task: traffic_forecasting
test_metric: test/mae
tod_emb_dim: 32
ts_emb_dim: 32
use_wandb: 0
val_metric: val/loss
var_num: 22
